#!/usr/bin/env python

import os
import glob
from unstdlib.standard.contextlib_ import open_atomic


fpath = lambda *a: os.path.join(os.path.dirname(__file__), *a)

def do_file(f):
    print "FILE: %s" %(f.name, )
    lines = (
        line for line in f
        if line.strip()
    )

    header = []
    for line in lines:
        if line[:1] != " ":
            break
        header.append(line)
    if header:
        print "HEADER:"
        print "".join(header)

    new_name = fpath(os.path.basename(f.name.replace(".txt", "-stripped.txt")))
    if os.path.exists(new_name.replace("-stripped.txt", "-stripped-done.txt")):
        continue
    with open_atomic(new_name) as outf:
        print outf.target_name
        for line in lines:
            if line[:1] != " ":
                line = line.split(None, 1)[-1]
            outf.write(line)


for fname in glob.glob(fpath("../*.txt")):
    with open(fname) as f:
        do_file(f)
